# Generated by Django 4.0.2 on 2022-04-04 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ramal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=255)),
                ('localizacao', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramais.ramal')),
            ],
        ),
    ]
